jaffle_shop:
  outputs:
    dev:
      dataset: jaffle_shop
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-keyfile
      location: US
      method: service-account
      priority: interactive
      project: practica-cloud-286009
      threads: 1
      type: bigquery
  target: dev